# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
workflows:
  version: 2
  build-test-and-deploy:
    jobs: 
      - test
      - build-deploy-prod:
          requires:
            - test
            - build-deploy-staging
          filters:
            branches:
              only:
                - master
      - build-deploy-staging:
          type: approval
          requires:
            - test
          filters:
            branches:
              only:
                - dev

jobs:
  test:
    working_directory: ~/repo
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Build css
          command: yarn build-css
      - run:
          name: Run test
          command: yarn test 

  build-deploy-prod: 
    working_directory: ~/repo
    docker:
      - image: efficienthealth/node-awscli:latest
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Run build
          command: yarn build
      - run:
          name: Sync to aws
          command: yarn sync

  build-deploy-staging: 
    working_directory: ~/repo
    docker:
      - image: efficienthealth/node-awscli:latest
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Run build
          command: yarn build
      - run:
          name: Sync to aws
          command: yarn sync:staging

