# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
workflows:
  version: 2
  build-test-and-deploy:
    jobs: 
      - test
      - build:
          filters:
            branches:
              ignore:
                - master
      - build-and-deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - master
jobs:
  test:
    working_directory: ~/repo
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Run test
          command: npm run test 
  build-and-deploy: 
    working_directory: ~/repo
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - run:
          name: install pip
          command: |
            sudo apt-get update
            sudo apt-get install -y python-dev python-pip
      - run:
          name: install aws cli
          command: sudo pip install awscli
      - run:
          name: Run build
          command: npm run build
      - run:
          name: Sync to aws
          command: npm run sync
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Run test
          command: npm run test
      - run:
          name: Run build
          command: npm run build




